# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'E-Bike App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
    pod 'GooglePlacesSearchController'
    pod 'Alamofire','~> 4.4'
    pod 'SwiftyJSON', :git => 'https://github.com/appsailor/SwiftyJSON.git', :branch => 'swift3'
    
  # Pods for E-Bike App

end
