platform :ios,'9.0'
use_frameworks!

target 'E-Bike App' do
	
	pod 'GooglePlaces'
		pod 'GooglePlacePicker'
		pod 'GoogleMaps'

	pod 'Alamofire','~> 4.4'
	pod 'SwiftyJSON', :git => 'https://github.com/appsailor/SwiftyJSON.git', :branch => 'swift3'

end
